;; Generated by :claw at 2021-06-27T21:10:12.837869+03:00
(asdf:defsystem #:claw-torch-bindings
  :description "Bindings generated by claw-torch"
  :author "CLAW"
  :license "Public domain"
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi :iffi)
  :components
  ((:file "bindings/x86_64-pc-linux-gnu" :if-feature
    (:and :x86-64 :linux))))